### ISSUE TITLE
Remove links to "Other Sites BCcampus Supports" in 'Pinboard' footer

### ISSUE THREAD

**Issue by dshaykewich** [BCcampus/bcc-sage#299] opened 2019-01-08 22:47 UTC
## Submit a feature request or bug report

- [ ] This is a feature request
- [X] This is a bug report
- [ ] This request isn't a duplicate of an [existing issue](https://github.com/BCcampus/bcc-sage/issues)
- [ ] You cleared your Web Browsers cache to ensure all new styling and images were loaded. 

---

**What is the current behavior?**
With the web consolidation project, a number of links in the footer in sites that use the Pinboard theme were made invalid.  

Please see: Remove links to "Other Sites BCcampus Supports" in footer of etug.ca" for details.
https://github.com/BCcampus/pinboard-child/issues/6

**What is the expected or desired behavior?**

Update footer to remove outdated liinks.

---

**Comment by bdolor** [comment] 2019-01-08 23:02
@dshaykewich - this looks like a duplicate of BCcampus/pinboard-child#6 and can't be solved by the bcc-sage theme?

**Comment by dshaykewich** [comment] 2019-01-08 23:08
@bdolor  - yes this references the other ticket.  I'd like to consider this for the BCcampus.ca sprint.  I just wanted to make sure it was in the list when we review issues for the sprint.  How would you like me to capture it?

**Comment by alex-418** [comment] 2019-01-24 00:07
Completed, please see https://github.com/BCcampus/pinboard-child/issues/6

**Comment by ehbeattie** [comment] 2019-01-24 00:19
This looks good on ETUG, will it be implemented across all BCcampus-hosted sites (BCTLC, etc.)?

**Comment by alex-418** [comment] 2019-01-24 00:31
@ehbeattie This change was only applied to etug.ca as requested in the issue details... but if there's any other sites that also need this gone, then I'd be glad to do that. including @dshaykewich as he may know which other ones this could apply to.

**Comment by ehbeattie** [comment] 2019-01-24 00:34
@alex-418 - ok, perfect. Thanks!

**Comment by dshaykewich** [comment] 2019-01-24 16:58
@ehbeattie , the only request I've had was to update the footer on etug.  I don't know what other sites use this theme.  Could you please provide a list of sites to update?

**Closed** 2019-01-26 04:18 UTC
Labels: SMALL - 1
