### ISSUE TITLE
Clicking the update button after editing a page routes the user to https://bccampus.ca/wp-admin/post.php

### ISSUE THREAD

**Issue by dshaykewich** [BCcampus/bcc-sage#285] opened 2018-11-07 19:48 UTC
## Submit a feature request or bug report

- [ ] This is a feature request
- [X] This is a bug report
- [ ] This request isn't a duplicate of an [existing issue](https://github.com/BCcampus/bcc-sage/issues)
- [ ] You cleared your Web Browsers cache to ensure all new styling and images were loaded. 

---

**What is the current behavior?**

After making an editing update to a page using the WordPress interface, clicking the "Update" button routes the user to
https://bccampus.ca/wp-admin/post.php
and shows an empty, white page (i.e., no content).

All content updates seem to be submitted and saved as expected, the user is simply directed to the wrong page.

![screen shot 2018-11-07 at 11 44 38 am](https://user-images.githubusercontent.com/43043264/48156775-f04cf000-e282-11e8-9eb9-54afcc79bf04.png)

![screen shot 2018-11-07 at 11 40 45 am](https://user-images.githubusercontent.com/43043264/48156800-fe027580-e282-11e8-9f81-d4d9666c945c.png)

**What is the expected or desired behavior?**

Updating a page should take the user back to the edit screen, per common Wordpress workflow.

---

## Bug report

**Where did the bug happen? Provide the link if possible**

Every WordPress edit form.

**Please provide steps to reproduce**

'Edit' a page
Make any change
'Update' the page

**Please describe your local environment:**

Web Browser name and version: FF 63

Operating System: Mac

**Comment by ehbeattie** [comment] 2018-11-08 00:40
This might not be an issue any longer. I was successful with all my page/post edits today and wasn't greeted by an empty, white page (of doom).

**Comment by bdolor** [comment] 2018-11-08 00:41
it is still an issue, I just solved it temporarily. I know what the problem is now but requires more than what I've done as a workaround.

**Comment by bdolor** [comment] 2018-11-08 18:42
resolved via https://github.com/BCcampus/bcc-sage/commit/7eee9e9f5e6b8ee66f9563d826157098d02f965e removed email notification, RC only.

**Closed** 2018-11-09 22:30 UTC
Labels: BIG - 7, bug
