### ISSUE TITLE
- Projects landing page: project content should not pull from the page

### ISSUE THREAD

**Issue by murphybarb** [BCcampus/bcc-sage#238] opened 2018-10-10 04:24 UTC
## Submit a feature request or bug report

- [x] This is a feature request
- [ ] This is a bug report
- [ ] This request isn't a duplicate of an [existing issue](https://github.com/BCcampus/bcc-sage/issues)
- [ ] You cleared your Web Browsers cache to ensure all new styling and images were loaded. 

---

**What is the current behavior?**

The content displaying for each project (located beside the image) is pulling from the individual project page. 

**What is the expected or desired behavior?**

We do not the content to pull from each individual page. We have specific content specifically written to appear to appear in this location and not pull from the page. 

Do I provide the content or can I update it? 

---

**Comment by bdolor** [comment] 2018-10-10 04:31
Updating this as a feature request. If it's not pulling from the content of an individual project page, then we're needing to look at another way (maybe custom fields/post metadata) to pull content that is in the control of content owners.

**Comment by bdolor** [comment] 2018-11-08 19:13
duplicate of #275

**Closed by bdolor** 2018-11-08 19:13 UTC
Labels: feature request
