### ISSUE TITLE
Set up hosting and an instance for an event microsite

### ISSUE THREAD

**Issue by ehbeattie** [BCcampus/bcc-sage#362] opened 2019-05-31 15:26 UTC
**Is your feature request related to a problem? Please describe.**
Host a microsite for Festival of Learning 2020

**Comment by alex-418** [comment] 2019-06-03 17:31
Domain name: festival.bccampus.ca 
Hosting: ASAP - Will get in touch with SFU about VM's. Plan B is to create a WP site on the multisite instance (troy/bccampus.ca)

**Comment by alex-418** [comment] 2019-06-06 16:45
Aiming to have this completed start of July.

**Comment by alex-418** [comment] 2019-06-25 18:40
FYI @dshaykewich spoke with @ehbeattie today about this. Since we don't yet have access to SFU cloud to create a new single-site WP instance for this, I'll be adding a site on the existing WP multisite with a temporary URL so they can move forward with this work by the end of this week. We can migrate this over to the new VM at a later date.

**Comment by dshaykewich** [comment] 2019-06-25 18:41
THanks @alex-418

**Comment by ehbeattie** [comment] 2019-06-26 14:17
Great, thanks!

**Comment by alex-418** [comment] 2019-06-27 17:13
@ehbeattie @dshaykewich I've created https://fol.troy.bccampus.ca/ and @stargraphicdesign should have got an e-mail to create her password. FTP access coming soon.

**Comment by alex-418** [comment] 2019-08-22 17:11
Resolved Aug 8th

**Comment by dshaykewich** [comment] 2019-09-17 20:57
@ehbeattie , could you please follow up with @stargraphicdesign about accessing the site on the BCc infrastructure?

**Comment by ehbeattie** [comment] 2019-09-17 20:59
@stargraphicdesign - please see above. Let me know where you are in the process and we will our best to assist.

Cheers

Erin

**Comment by dshaykewich** [comment] 2019-09-17 21:04
@alex-418 , is there anything more that needs to be done for the domain name?  I see that it currently redirects to the 2018 event page (https://bccampus.ca/events/events-archive/festival-of-learning-2018/)

**Comment by alex-418** [comment] 2019-09-18 00:12
@ehbeattie @dshaykewich Caught up with the e-mail thread between @stargraphicdesign and @georgemeyer on migration plan:

Please **do not** use this plugin, it will fail. The documentation says it must be the same WP installation as the backup, and _cannot_ be used to migrate a site which is what we're trying to accomplish. Please see https://updraftplus.com/restoring-single-sites-on-network/ 

I confirmed this by looking at the database it would import, and you can see it would over-write our production database with the following settings, effectively taking down all of our sites: 

![db](https://user-images.githubusercontent.com/17072191/65088165-206a2280-d96d-11e9-8d5d-a0690070b2b1.png)

What we need is to bring in the following, which can be done using WordPress built in tools:
- The custom theme
- The plugins 
- The content 

The only thing missing would be any custom configuration in the theme and plugins. This cannot be brought over unless the plugin supports this. 

I can bring in the Theme and Plugins required. For the content @stargraphicdesign can export/import using the WP built in tool. Let me know if you have any questions about that and I can help walk you through that, happy to screen share. 

We should schedule this to make it all happen quickly and efficiently, along with a snapshot of the server, in case we need to roll back.

For the domain, we have to change the redirect to point to the new site, and configure the domain in WP. Let's keep all conversation here so none of this gets lost, let me know if you have any questions or concerns happy to make myself available.

**Comment by alex-418** [comment] 2019-09-18 03:44
@stargraphicdesign I've brought in and activated the festival2020 theme and ACF Pro plugin to https://fol.troy.bccampus.ca ... the only thing left from your end is to export/import the content, create and assign your menus, and configure the theme and plugin.

**Theme:**
Are there any other steps that your [theme framework](https://jointswp.com/) requires? I can see the vendor folder is included, and that you chose the CSS version. So I don't think I have to worry about compiling Sass/Assets, or installing dependencies? Please correct me if i'm wrong about that and I can `npm run build` if needed. 

**ACF Plugin License:**
The ACF pro included in this, requires a valid license to receive updates. I'd prefer to avoid creating dependencies on paid plugins if the functionality can be achieved using [built-in functionality](https://wordpress.org/support/article/custom-fields/). I can see the theme you chose requires this, so doubt we can avoid it in this case? If you're interested in changing this, I'd be glad to show you how easy it can be to create custom fields, and retrieve the values for use in your template files. Otherwise @ehbeattie probably a good idea to ensure we have purchased a valid license to get the updates.

**Domain:** 
@ehbeattie once the sites is looking how you want on our server, let us know when you want to launch, and we'll coordinate the domain name change (@dshaykewich is working on planning that change). You wanted to stick with `festival.bccampus.ca` correct?

P.S. I had previously closed this issue because I thought it had been resolved via an e-mail thread... glad to leave open until it's actually completed.

**Comment by alex-418** [comment] 2019-09-18 05:12
@ehbeattie @stargraphicdesign Good news, I was able to get https://festival.bccampus.ca domain working without much effort because the DNS entry already existed, and we were re-directing it in our servers configuration (Please clear your browsers cache if it's not working). 

 @dshaykewich I just had to remove the `301` rewrite rule from `httpd.conf` on our server and reload the httpd service. (Looks like requesting a new DNS entry for a subdomain via SFU takes ~2weeks turn-around.) 
![httpdconf](https://user-images.githubusercontent.com/17072191/65112888-f11bdb80-d995-11e9-8c0f-e67f83774352.png)

**Comment by stargraphicdesign** [comment] 2019-09-18 17:03
Thanks everyone
- i've configured everything and brought the content over. there's a few bugs that are only appearing on this version that i'll need to work out. 

- to answer your question about the theme, nothing else required on your end as long as all the files contained in that folder made it over. the site is super minimal and fast loading so there shouldnt be any need to minify any of the css or js files

- I have a premium licence for ACF, so i've entered my license key, it's good for life so nothing required on your end now or in the future.

- One big issue i have is that i need to be able to make changes to the theme and theme's styling as we fill out the rest of the pages some will be getting some additional css elements and potentially some new custom fields. My plan was to work on things over on my dev site and just paste them into the theme files in Appearance>Theme Editor when ready, but that section is completely missing from the wordpress admin. How do you prefer i do this?

**Comment by alex-418** [comment] 2019-09-18 17:25
Thanks @stargraphicdesign for sorting out that license key. 

The Theme editor feature is missing because the [iThemes Security](https://en-ca.wordpress.org/plugins/better-wp-security/) installed locks that down. I have tried disabling this temporarily in the past as per docs but to no avail. 

Assuming you didn't get FTP access, so instead you can place any custom CSS in `Appearance -> Customize -> Additional CSS ` to get it looking exactly how you like. I'll copy this over to the themes style sheet once you're all done. Please let me know if you need help with anything else. 

![css](https://user-images.githubusercontent.com/17072191/65170552-c9f8f480-d9fd-11e9-9276-5c02115b26b9.png)

**Comment by stargraphicdesign** [comment] 2019-09-18 18:23
That's just going to make the css file messy. Plus it still doesn't solve the issue of adding new page templates and page custom fields.  I'll have to re-send you the entire theme.

**Comment by alex-418** [comment] 2019-09-18 19:26
Hi @stargraphicdesign if the theme is not yet completed, then I agree it will be easier for you to send that over once it's all finished. If you want FTP access instead, then please follow up on the e-mail thread with George.

**Comment by alex-418** [comment] 2019-10-10 21:33
@ehbeattie This is live at Festival.BCcampus.ca and @stargraphicdesign sent me a theme update today which has been applied. If there's nothing further needed here, can we close this issue? Please do let me know if you need anything else from me on this one.

**Closed** 2019-10-10 21:35 UTC
